// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_event_comp_Button3_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_Button3 = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_uiStandListPanel, _UI_BASIC_PROPERTY_HEIGHT,  20);
    }
}

// COMPONENT Button3

lv_obj_t * ui_Button3_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Button3;
    cui_Button3 = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_Button3, 42);
    lv_obj_set_height(cui_Button3, 23);
    lv_obj_set_x(cui_Button3, 131);
    lv_obj_set_y(cui_Button3, -58);
    lv_obj_set_align(cui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON3_NUM);
    children[UI_COMP_BUTTON3_BUTTON3] = cui_Button3;
    lv_obj_add_event_cb(cui_Button3, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Button3, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Button3, ui_event_comp_Button3_Button3, LV_EVENT_ALL, children);
    ui_comp_Button3_create_hook(cui_Button3);
    return cui_Button3;
}

