// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT LEDSettings

lv_obj_t * ui_LEDSettings_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_LEDSettings;
    cui_LEDSettings = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_LEDSettings);
    lv_obj_set_width(cui_LEDSettings, 287);
    lv_obj_set_height(cui_LEDSettings, 181);
    lv_obj_set_x(cui_LEDSettings, -102);
    lv_obj_set_y(cui_LEDSettings, 111);
    lv_obj_set_align(cui_LEDSettings, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_LEDSettings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_ColourWheel;
    cui_ColourWheel = lv_label_create(cui_LEDSettings);
    lv_obj_set_width(cui_ColourWheel, 117);
    lv_obj_set_height(cui_ColourWheel, 14);
    lv_obj_set_x(cui_ColourWheel, -72);
    lv_obj_set_y(cui_ColourWheel, -70);
    lv_obj_set_align(cui_ColourWheel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_ColourWheel, "Colour Wheel");

    lv_obj_t * cui_Colorwheel1;
    cui_Colorwheel1 = lv_colorwheel_create(cui_LEDSettings, true);
    lv_obj_set_width(cui_Colorwheel1, 124);
    lv_obj_set_height(cui_Colorwheel1, 120);
    lv_obj_set_x(cui_Colorwheel1, -74);
    lv_obj_set_y(cui_Colorwheel1, 9);
    lv_obj_set_align(cui_Colorwheel1, LV_ALIGN_CENTER);

    lv_obj_t * cui_labelBrightness;
    cui_labelBrightness = lv_label_create(cui_LEDSettings);
    lv_obj_set_width(cui_labelBrightness, 117);
    lv_obj_set_height(cui_labelBrightness, 14);
    lv_obj_set_x(cui_labelBrightness, 68);
    lv_obj_set_y(cui_labelBrightness, -70);
    lv_obj_set_align(cui_labelBrightness, LV_ALIGN_CENTER);
    lv_label_set_text(cui_labelBrightness, "Brightness");

    lv_obj_t * cui_Brightness;
    cui_Brightness = lv_slider_create(cui_LEDSettings);
    lv_slider_set_value(cui_Brightness, 10, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_Brightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(cui_Brightness, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_Brightness, 102);
    lv_obj_set_height(cui_Brightness, 10);
    lv_obj_set_x(cui_Brightness, 67);
    lv_obj_set_y(cui_Brightness, -35);
    lv_obj_set_align(cui_Brightness, LV_ALIGN_CENTER);

    lv_obj_t * cui_labelBrightness1;
    cui_labelBrightness1 = lv_label_create(cui_LEDSettings);
    lv_obj_set_width(cui_labelBrightness1, 117);
    lv_obj_set_height(cui_labelBrightness1, 14);
    lv_obj_set_x(cui_labelBrightness1, 68);
    lv_obj_set_y(cui_labelBrightness1, -3);
    lv_obj_set_align(cui_labelBrightness1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_labelBrightness1, "Speed");

    lv_obj_t * cui_Speed;
    cui_Speed = lv_slider_create(cui_LEDSettings);
    lv_slider_set_value(cui_Speed, 10, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_Speed) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(cui_Speed, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_Speed, 102);
    lv_obj_set_height(cui_Speed, 10);
    lv_obj_set_x(cui_Speed, 67);
    lv_obj_set_y(cui_Speed, 27);
    lv_obj_set_align(cui_Speed, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LEDSETTINGS_NUM);
    children[UI_COMP_LEDSETTINGS_LEDSETTINGS] = cui_LEDSettings;
    children[UI_COMP_LEDSETTINGS_COLOURWHEEL] = cui_ColourWheel;
    children[UI_COMP_LEDSETTINGS_COLORWHEEL1] = cui_Colorwheel1;
    children[UI_COMP_LEDSETTINGS_LABELBRIGHTNESS] = cui_labelBrightness;
    children[UI_COMP_LEDSETTINGS_BRIGHTNESS] = cui_Brightness;
    children[UI_COMP_LEDSETTINGS_LABELBRIGHTNESS1] = cui_labelBrightness1;
    children[UI_COMP_LEDSETTINGS_SPEED] = cui_Speed;
    lv_obj_add_event_cb(cui_LEDSettings, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_LEDSettings, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_LEDSettings_create_hook(cui_LEDSettings);
    return cui_LEDSettings;
}

