// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_comp_barMenu_create_hook(lv_obj_t * comp)
{
}

void ui_comp_btnMinimise_create_hook(lv_obj_t * comp)
{
}

void ui_comp_LEDSettings_create_hook(lv_obj_t * comp)
{
}
