// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_BTNMINIMISE_H
#define _UI_COMP_BTNMINIMISE_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT btnMinimise
#define UI_COMP_BTNMINIMISE_BTNMINIMISE 0
#define UI_COMP_BTNMINIMISE_LABEL1 1
#define _UI_COMP_BTNMINIMISE_NUM 2
lv_obj_t * ui_btnMinimise_create(lv_obj_t * comp_parent);
void ui_event_comp_btnMinimise_btnMinimise(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
