// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_labelYmax;
lv_obj_t * uic_valueYMax;
lv_obj_t * uic_ymindown;
lv_obj_t * uic_ymaxdown;
lv_obj_t * uic_yminup;
lv_obj_t * uic_ymaxup;
lv_obj_t * uic_valueYOffSetValue;
lv_obj_t * uic_labelXmax;
lv_obj_t * uic_valueXmin;
lv_obj_t * uic_labelXOffSetValue;
lv_obj_t * uic_xmindown;
lv_obj_t * uic_xmaxdown;
lv_obj_t * uic_xminup;
lv_obj_t * uic_xmaxup;
lv_obj_t * ui_Calibrate = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_xmaxup = NULL;
lv_obj_t * ui_xminup = NULL;
lv_obj_t * ui_xmaxdown = NULL;
lv_obj_t * ui_xmindown = NULL;
lv_obj_t * ui_labelXOffSetValue = NULL;
lv_obj_t * ui_valueXmin = NULL;
lv_obj_t * ui_labelXmax = NULL;
lv_obj_t * ui_valueXMax = NULL;
lv_obj_t * ui_ymaxup = NULL;
lv_obj_t * ui_yminup = NULL;
lv_obj_t * ui_ymaxdown = NULL;
lv_obj_t * ui_ymindown = NULL;
lv_obj_t * ui_labelXOffSetValue1 = NULL;
lv_obj_t * ui_valueXmin1 = NULL;
lv_obj_t * ui_valueYMax = NULL;
lv_obj_t * ui_labelYmax = NULL;
// event funtions
void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_xmaxup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        x_max_up(e);
    }
}

void ui_event_xminup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        x_min_up(e);
    }
}

void ui_event_xmaxdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        x_max_down(e);
    }
}

void ui_event_xmindown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        x_min_down(e);
    }
}

void ui_event_ymaxup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        y_max_up(e);
    }
}

void ui_event_yminup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        y_min_up(e);
    }
}

void ui_event_ymaxdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        y_max_down(e);
    }
}

void ui_event_ymindown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        y_min_down(e);
    }
}

// build funtions

void ui_Calibrate_screen_init(void)
{
    ui_Calibrate = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Calibrate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_Calibrate);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 100);
    lv_obj_set_height(ui_Container3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container3, -105);
    lv_obj_set_y(ui_Container3, -100);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button8 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Button8, 56);
    lv_obj_set_height(ui_Button8, 27);
    lv_obj_set_x(ui_Button8, -11);
    lv_obj_set_y(ui_Button8, -5);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0x01A206), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xmaxup = lv_btn_create(ui_Calibrate);
    lv_obj_set_width(ui_xmaxup, 50);
    lv_obj_set_height(ui_xmaxup, 50);
    lv_obj_set_x(ui_xmaxup, -52);
    lv_obj_set_y(ui_xmaxup, 86);
    lv_obj_set_align(ui_xmaxup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_xmaxup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_xmaxup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_xmaxup, lv_color_hex(0x16A600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_xmaxup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xminup = lv_btn_create(ui_Calibrate);
    lv_obj_set_width(ui_xminup, 50);
    lv_obj_set_height(ui_xminup, 50);
    lv_obj_set_x(ui_xminup, -49);
    lv_obj_set_y(ui_xminup, 32);
    lv_obj_set_align(ui_xminup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_xminup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_xminup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_xminup, lv_color_hex(0x16A600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_xminup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xmaxdown = lv_btn_create(ui_Calibrate);
    lv_obj_set_width(ui_xmaxdown, 50);
    lv_obj_set_height(ui_xmaxdown, 50);
    lv_obj_set_x(ui_xmaxdown, 13);
    lv_obj_set_y(ui_xmaxdown, 87);
    lv_obj_set_align(ui_xmaxdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_xmaxdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_xmaxdown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_xmaxdown, lv_color_hex(0xE10000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_xmaxdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xmindown = lv_btn_create(ui_Calibrate);
    lv_obj_set_width(ui_xmindown, 50);
    lv_obj_set_height(ui_xmindown, 50);
    lv_obj_set_x(ui_xmindown, 15);
    lv_obj_set_y(ui_xmindown, 34);
    lv_obj_set_align(ui_xmindown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_xmindown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_xmindown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_xmindown, lv_color_hex(0xE10000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_xmindown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelXOffSetValue = lv_label_create(ui_Calibrate);
    lv_obj_set_width(ui_labelXOffSetValue, 137);
    lv_obj_set_height(ui_labelXOffSetValue, 19);
    lv_obj_set_x(ui_labelXOffSetValue, -81);
    lv_obj_set_y(ui_labelXOffSetValue, 25);
    lv_obj_set_align(ui_labelXOffSetValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelXOffSetValue, "X Min:");

    ui_valueXmin = lv_label_create(ui_Calibrate);
    lv_obj_set_width(ui_valueXmin, 105);
    lv_obj_set_height(ui_valueXmin, 19);
    lv_obj_set_x(ui_valueXmin, -96);
    lv_obj_set_y(ui_valueXmin, 46);
    lv_obj_set_align(ui_valueXmin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueXmin, ".");

    ui_labelXmax = lv_label_create(ui_Calibrate);
    lv_obj_set_width(ui_labelXmax, 137);
    lv_obj_set_height(ui_labelXmax, 19);
    lv_obj_set_x(ui_labelXmax, -79);
    lv_obj_set_y(ui_labelXmax, 89);
    lv_obj_set_align(ui_labelXmax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelXmax, "X Max:");

    ui_valueXMax = lv_label_create(ui_Calibrate);
    lv_obj_set_width(ui_valueXMax, 137);
    lv_obj_set_height(ui_valueXMax, 19);
    lv_obj_set_x(ui_valueXMax, -78);
    lv_obj_set_y(ui_valueXMax, 108);
    lv_obj_set_align(ui_valueXMax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueXMax, ".");

    ui_ymaxup = lv_btn_create(ui_Calibrate);
    lv_obj_set_width(ui_ymaxup, 50);
    lv_obj_set_height(ui_ymaxup, 50);
    lv_obj_set_x(ui_ymaxup, -52);
    lv_obj_set_y(ui_ymaxup, -26);
    lv_obj_set_align(ui_ymaxup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ymaxup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ymaxup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ymaxup, lv_color_hex(0x16A600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ymaxup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yminup = lv_btn_create(ui_Calibrate);
    lv_obj_set_width(ui_yminup, 50);
    lv_obj_set_height(ui_yminup, 50);
    lv_obj_set_x(ui_yminup, -31);
    lv_obj_set_y(ui_yminup, -86);
    lv_obj_set_align(ui_yminup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yminup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_yminup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_yminup, lv_color_hex(0x16A600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_yminup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ymaxdown = lv_btn_create(ui_Calibrate);
    lv_obj_set_width(ui_ymaxdown, 50);
    lv_obj_set_height(ui_ymaxdown, 50);
    lv_obj_set_x(ui_ymaxdown, 9);
    lv_obj_set_y(ui_ymaxdown, -22);
    lv_obj_set_align(ui_ymaxdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ymaxdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ymaxdown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ymaxdown, lv_color_hex(0xE10000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ymaxdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ymindown = lv_btn_create(ui_Calibrate);
    lv_obj_set_width(ui_ymindown, 50);
    lv_obj_set_height(ui_ymindown, 50);
    lv_obj_set_x(ui_ymindown, 31);
    lv_obj_set_y(ui_ymindown, -83);
    lv_obj_set_align(ui_ymindown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ymindown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ymindown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ymindown, lv_color_hex(0xE10000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ymindown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelXOffSetValue1 = lv_label_create(ui_Calibrate);
    lv_obj_set_width(ui_labelXOffSetValue1, 137);
    lv_obj_set_height(ui_labelXOffSetValue1, 19);
    lv_obj_set_x(ui_labelXOffSetValue1, -84);
    lv_obj_set_y(ui_labelXOffSetValue1, -76);
    lv_obj_set_align(ui_labelXOffSetValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelXOffSetValue1, "y Min:");

    ui_valueXmin1 = lv_label_create(ui_Calibrate);
    lv_obj_set_width(ui_valueXmin1, 105);
    lv_obj_set_height(ui_valueXmin1, 19);
    lv_obj_set_x(ui_valueXmin1, -97);
    lv_obj_set_y(ui_valueXmin1, -56);
    lv_obj_set_align(ui_valueXmin1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueXmin1, ".");

    ui_valueYMax = lv_label_create(ui_Calibrate);
    lv_obj_set_width(ui_valueYMax, 137);
    lv_obj_set_height(ui_valueYMax, 19);
    lv_obj_set_x(ui_valueYMax, -83);
    lv_obj_set_y(ui_valueYMax, -10);
    lv_obj_set_align(ui_valueYMax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valueYMax, ".");

    ui_labelYmax = lv_label_create(ui_Calibrate);
    lv_obj_set_width(ui_labelYmax, 137);
    lv_obj_set_height(ui_labelYmax, 19);
    lv_obj_set_x(ui_labelYmax, -83);
    lv_obj_set_y(ui_labelYmax, -35);
    lv_obj_set_align(ui_labelYmax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelYmax, "y Max:");

    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_xmaxup, ui_event_xmaxup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_xminup, ui_event_xminup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_xmaxdown, ui_event_xmaxdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_xmindown, ui_event_xmindown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ymaxup, ui_event_ymaxup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_yminup, ui_event_yminup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ymaxdown, ui_event_ymaxdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ymindown, ui_event_ymindown, LV_EVENT_ALL, NULL);
    uic_xmaxup = ui_xmaxup;
    uic_xminup = ui_xminup;
    uic_xmaxdown = ui_xmaxdown;
    uic_xmindown = ui_xmindown;
    uic_labelXOffSetValue = ui_labelXOffSetValue;
    uic_valueXmin = ui_valueXmin;
    uic_labelXmax = ui_labelXmax;
    uic_valueYOffSetValue = ui_valueXMax;
    uic_ymaxup = ui_ymaxup;
    uic_yminup = ui_yminup;
    uic_ymaxdown = ui_ymaxdown;
    uic_ymindown = ui_ymindown;
    uic_valueYMax = ui_valueYMax;
    uic_labelYmax = ui_labelYmax;

}

void ui_Calibrate_screen_destroy(void)
{
    if(ui_Calibrate) lv_obj_del(ui_Calibrate);

    // NULL screen variables
    ui_Calibrate = NULL;
    ui_Container3 = NULL;
    ui_Button8 = NULL;
    uic_xmaxup = NULL;
    ui_xmaxup = NULL;
    uic_xminup = NULL;
    ui_xminup = NULL;
    uic_xmaxdown = NULL;
    ui_xmaxdown = NULL;
    uic_xmindown = NULL;
    ui_xmindown = NULL;
    uic_labelXOffSetValue = NULL;
    ui_labelXOffSetValue = NULL;
    uic_valueXmin = NULL;
    ui_valueXmin = NULL;
    uic_labelXmax = NULL;
    ui_labelXmax = NULL;
    uic_valueYOffSetValue = NULL;
    ui_valueXMax = NULL;
    uic_ymaxup = NULL;
    ui_ymaxup = NULL;
    uic_yminup = NULL;
    ui_yminup = NULL;
    uic_ymaxdown = NULL;
    ui_ymaxdown = NULL;
    uic_ymindown = NULL;
    ui_ymindown = NULL;
    ui_labelXOffSetValue1 = NULL;
    ui_valueXmin1 = NULL;
    uic_valueYMax = NULL;
    ui_valueYMax = NULL;
    uic_labelYmax = NULL;
    ui_labelYmax = NULL;

}
