// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_event_comp_btnMinimise_btnMinimise(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_btnMinimise = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_uiStandListPanel, _UI_BASIC_PROPERTY_HEIGHT,  20);
    }
}

// COMPONENT btnMinimise

lv_obj_t * ui_btnMinimise_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_btnMinimise;
    cui_btnMinimise = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_btnMinimise, 27);
    lv_obj_set_height(cui_btnMinimise, 23);
    lv_obj_set_x(cui_btnMinimise, 67);
    lv_obj_set_y(cui_btnMinimise, -57);
    lv_obj_set_align(cui_btnMinimise, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_btnMinimise, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_btnMinimise, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_btnMinimise, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_btnMinimise, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_btnMinimise, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label1;
    cui_Label1 = lv_label_create(cui_btnMinimise);
    lv_obj_set_width(cui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label1, "-");
    lv_label_set_recolor(cui_Label1, "true");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BTNMINIMISE_NUM);
    children[UI_COMP_BTNMINIMISE_BTNMINIMISE] = cui_btnMinimise;
    children[UI_COMP_BTNMINIMISE_LABEL1] = cui_Label1;
    lv_obj_add_event_cb(cui_btnMinimise, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_btnMinimise, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_btnMinimise, ui_event_comp_btnMinimise_btnMinimise, LV_EVENT_ALL, children);
    ui_comp_btnMinimise_create_hook(cui_btnMinimise);
    return cui_btnMinimise;
}

