// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void force_recalibrate(lv_event_t * e)
{
	// Your code here
}

void x_max_up(lv_event_t * e)
{
	// Your code here
}

void x_min_up(lv_event_t * e)
{
	// Your code here
}

void x_max_down(lv_event_t * e)
{
	// Your code here
}

void x_min_down(lv_event_t * e)
{
	// Your code here
}

void y_max_up(lv_event_t * e)
{
	// Your code here
}

void y_min_up(lv_event_t * e)
{
	// Your code here
}

void y_max_down(lv_event_t * e)
{
	// Your code here
}

void y_min_down(lv_event_t * e)
{
	// Your code here
}
