// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void x_max_up(lv_event_t * e);
void x_min_up(lv_event_t * e);
void x_max_down(lv_event_t * e);
void x_min_down(lv_event_t * e);
void y_max_up(lv_event_t * e);
void y_min_up(lv_event_t * e);
void y_max_down(lv_event_t * e);
void y_min_down(lv_event_t * e);
void force_recalibrate(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
