// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_event_comp_barMenu_btnHome1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_barMenu = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
    }
}

// COMPONENT barMenu

lv_obj_t * ui_barMenu_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_barMenu;
    cui_barMenu = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_barMenu);
    lv_obj_set_width(cui_barMenu, lv_pct(100));
    lv_obj_set_height(cui_barMenu, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_barMenu, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_barMenu, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_barMenu, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_barMenu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_btnHome1;
    cui_btnHome1 = lv_btn_create(cui_barMenu);
    lv_obj_set_width(cui_btnHome1, 63);
    lv_obj_set_height(cui_btnHome1, 27);
    lv_obj_set_x(cui_btnHome1, 0);
    lv_obj_set_y(cui_btnHome1, 2);
    lv_obj_set_align(cui_btnHome1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_btnHome1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_btnHome1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_btnHome1, lv_color_hex(0x01A206), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_btnHome1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_btnHome1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_btnHome1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_btnHome1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label2;
    cui_Label2 = lv_label_create(cui_btnHome1);
    lv_obj_set_width(cui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label2, "Home");

    lv_obj_t * cui_Container1;
    cui_Container1 = lv_obj_create(cui_barMenu);
    lv_obj_remove_style_all(cui_Container1);
    lv_obj_set_width(cui_Container1, 250);
    lv_obj_set_height(cui_Container1, 27);
    lv_obj_set_align(cui_Container1, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(cui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container1, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_datetime;
    cui_datetime = lv_label_create(cui_Container1);
    lv_obj_set_height(cui_datetime, 20);
    lv_obj_set_width(cui_datetime, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(cui_datetime, 246);
    lv_obj_set_y(cui_datetime, 43);
    lv_obj_set_align(cui_datetime, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(cui_datetime, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_datetime, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_label_set_text(cui_datetime, "unset");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BARMENU_NUM);
    children[UI_COMP_BARMENU_BARMENU] = cui_barMenu;
    children[UI_COMP_BARMENU_BTNHOME1] = cui_btnHome1;
    children[UI_COMP_BARMENU_BTNHOME1_LABEL2] = cui_Label2;
    children[UI_COMP_BARMENU_CONTAINER1] = cui_Container1;
    children[UI_COMP_BARMENU_CONTAINER1_DATETIME] = cui_datetime;
    lv_obj_add_event_cb(cui_barMenu, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_barMenu, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_btnHome1, ui_event_comp_barMenu_btnHome1, LV_EVENT_ALL, children);
    ui_comp_barMenu_create_hook(cui_barMenu);
    return cui_barMenu;
}

