// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CALIBRATE_H
#define UI_CALIBRATE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Calibrate
extern void ui_Calibrate_screen_init(void);
extern void ui_Calibrate_screen_destroy(void);
extern lv_obj_t * ui_Calibrate;
extern lv_obj_t * ui_Container3;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern void ui_event_xmaxup(lv_event_t * e);
extern lv_obj_t * ui_xmaxup;
extern void ui_event_xminup(lv_event_t * e);
extern lv_obj_t * ui_xminup;
extern void ui_event_xmaxdown(lv_event_t * e);
extern lv_obj_t * ui_xmaxdown;
extern void ui_event_xmindown(lv_event_t * e);
extern lv_obj_t * ui_xmindown;
extern lv_obj_t * ui_labelXOffSetValue;
extern lv_obj_t * ui_valueXmin;
extern lv_obj_t * ui_labelXmax;
extern lv_obj_t * ui_valueXMax;
extern void ui_event_ymaxup(lv_event_t * e);
extern lv_obj_t * ui_ymaxup;
extern void ui_event_yminup(lv_event_t * e);
extern lv_obj_t * ui_yminup;
extern void ui_event_ymaxdown(lv_event_t * e);
extern lv_obj_t * ui_ymaxdown;
extern void ui_event_ymindown(lv_event_t * e);
extern lv_obj_t * ui_ymindown;
extern lv_obj_t * ui_labelXOffSetValue1;
extern lv_obj_t * ui_valueXmin1;
extern lv_obj_t * ui_valueYMax;
extern lv_obj_t * ui_labelYmax;
// CUSTOM VARIABLES
extern lv_obj_t * uic_xmaxup;
extern lv_obj_t * uic_xminup;
extern lv_obj_t * uic_xmaxdown;
extern lv_obj_t * uic_xmindown;
extern lv_obj_t * uic_labelXOffSetValue;
extern lv_obj_t * uic_valueXmin;
extern lv_obj_t * uic_labelXmax;
extern lv_obj_t * uic_valueYOffSetValue;
extern lv_obj_t * uic_ymaxup;
extern lv_obj_t * uic_yminup;
extern lv_obj_t * uic_ymaxdown;
extern lv_obj_t * uic_ymindown;
extern lv_obj_t * uic_valueYMax;
extern lv_obj_t * uic_labelYmax;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

