// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_LEDSETTINGS_H
#define _UI_COMP_LEDSETTINGS_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT LEDSettings
#define UI_COMP_LEDSETTINGS_LEDSETTINGS 0
#define UI_COMP_LEDSETTINGS_COLOURWHEEL 1
#define UI_COMP_LEDSETTINGS_COLORWHEEL1 2
#define UI_COMP_LEDSETTINGS_LABELBRIGHTNESS 3
#define UI_COMP_LEDSETTINGS_BRIGHTNESS 4
#define UI_COMP_LEDSETTINGS_LABELBRIGHTNESS1 5
#define UI_COMP_LEDSETTINGS_SPEED 6
#define _UI_COMP_LEDSETTINGS_NUM 7
lv_obj_t * ui_LEDSettings_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
