// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_BARMENU_H
#define _UI_COMP_BARMENU_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT barMenu
#define UI_COMP_BARMENU_BARMENU 0
#define UI_COMP_BARMENU_BTNHOME1 1
#define UI_COMP_BARMENU_BTNHOME1_LABEL2 2
#define UI_COMP_BARMENU_CONTAINER1 3
#define UI_COMP_BARMENU_CONTAINER1_DATETIME 4
#define _UI_COMP_BARMENU_NUM 5
lv_obj_t * ui_barMenu_create(lv_obj_t * comp_parent);
void ui_event_comp_barMenu_btnHome1(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
