// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_AnimDropdown;
lv_obj_t * uic_ColourWheel;
lv_obj_t * uic_CheckboxStand2;
lv_obj_t * uic_CheckboxStand1;
lv_obj_t * uic_uiStandListPanel;
lv_obj_t * uic_ScreenLEDs;
lv_obj_t * ui_ScreenLEDs = NULL;
lv_obj_t * ui_barMenu = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_uiStandListPanel = NULL;
lv_obj_t * ui_CheckboxStand1 = NULL;
lv_obj_t * ui_CheckboxStand2 = NULL;
lv_obj_t * ui_ColourWheel = NULL;
lv_obj_t * ui_AnimDropdown = NULL;
lv_obj_t * ui_LEDSettings = NULL;
// event funtions

// build funtions

void ui_ScreenLEDs_screen_init(void)
{
    ui_ScreenLEDs = lv_obj_create(NULL);
    lv_obj_add_flag(ui_ScreenLEDs, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_clear_flag(ui_ScreenLEDs, LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_ScreenLEDs, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_flex_flow(ui_ScreenLEDs, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenLEDs, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(ui_ScreenLEDs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ScreenLEDs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barMenu = ui_barMenu_create(ui_ScreenLEDs);
    lv_obj_set_x(ui_barMenu, 0);
    lv_obj_set_y(ui_barMenu, 0);

    ui_Container2 = lv_obj_create(ui_ScreenLEDs);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 320);
    lv_obj_set_height(ui_Container2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Container2, 13);
    lv_obj_set_y(ui_Container2, 81);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = ui_btnMinimise_create(ui_Container2);
    lv_obj_set_x(ui_Button3, 100);
    lv_obj_set_y(ui_Button3, -56);

    ui_uiStandListPanel = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_uiStandListPanel, lv_pct(100));
    lv_obj_set_height(ui_uiStandListPanel, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_x(ui_uiStandListPanel, 0);
    lv_obj_set_y(ui_uiStandListPanel, 16);
    lv_obj_set_align(ui_uiStandListPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiStandListPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiStandListPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_uiStandListPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiStandListPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxStand1 = lv_checkbox_create(ui_uiStandListPanel);
    lv_obj_set_width(ui_CheckboxStand1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxStand1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxStand1, -89);
    lv_obj_set_y(ui_CheckboxStand1, -23);
    lv_obj_set_align(ui_CheckboxStand1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CheckboxStand1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_CheckboxStand1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_CheckboxStand1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_CheckboxStand2 = lv_checkbox_create(ui_uiStandListPanel);
    lv_obj_set_width(ui_CheckboxStand2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxStand2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxStand2, 69);
    lv_obj_set_y(ui_CheckboxStand2, 15);
    lv_obj_set_align(ui_CheckboxStand2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxStand2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ColourWheel = lv_obj_create(ui_ScreenLEDs);
    lv_obj_set_width(ui_ColourWheel, lv_pct(100));
    lv_obj_set_height(ui_ColourWheel, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_flex_flow(ui_ColourWheel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ColourWheel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ColourWheel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ColourWheel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AnimDropdown = lv_dropdown_create(ui_ColourWheel);
    lv_obj_set_width(ui_AnimDropdown, 288);
    lv_obj_set_height(ui_AnimDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AnimDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AnimDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_LEDSettings = ui_LEDSettings_create(ui_ColourWheel);
    lv_obj_set_x(ui_LEDSettings, -102);
    lv_obj_set_y(ui_LEDSettings, 110);

    uic_ScreenLEDs = ui_ScreenLEDs;
    uic_uiStandListPanel = ui_uiStandListPanel;
    uic_CheckboxStand1 = ui_CheckboxStand1;
    uic_CheckboxStand2 = ui_CheckboxStand2;
    uic_ColourWheel = ui_ColourWheel;
    uic_AnimDropdown = ui_AnimDropdown;

}

void ui_ScreenLEDs_screen_destroy(void)
{
    if(ui_ScreenLEDs) lv_obj_del(ui_ScreenLEDs);

    // NULL screen variables
    uic_ScreenLEDs = NULL;
    ui_ScreenLEDs = NULL;
    ui_barMenu = NULL;
    ui_Container2 = NULL;
    ui_Button3 = NULL;
    uic_uiStandListPanel = NULL;
    ui_uiStandListPanel = NULL;
    uic_CheckboxStand1 = NULL;
    ui_CheckboxStand1 = NULL;
    uic_CheckboxStand2 = NULL;
    ui_CheckboxStand2 = NULL;
    uic_ColourWheel = NULL;
    ui_ColourWheel = NULL;
    uic_AnimDropdown = NULL;
    ui_AnimDropdown = NULL;
    ui_LEDSettings = NULL;

}
