// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENHOME_H
#define UI_SCREENHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenHome
extern void ui_ScreenHome_screen_init(void);
extern void ui_ScreenHome_screen_destroy(void);
extern lv_obj_t * ui_ScreenHome;
extern void ui_event_LEDs(lv_event_t * e);
extern lv_obj_t * ui_LEDs;
extern lv_obj_t * ui_labelLEDs;
extern lv_obj_t * ui_Brightness2;
extern void ui_event_Calibration(lv_event_t * e);
extern lv_obj_t * ui_Calibration;
extern void ui_event_labelCalbration(lv_event_t * e);
extern lv_obj_t * ui_labelCalbration;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenHome;
extern lv_obj_t * uic_LEDs;
extern lv_obj_t * uic_labelLEDs;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

