// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENLEDS_H
#define UI_SCREENLEDS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenLEDs
extern void ui_ScreenLEDs_screen_init(void);
extern void ui_ScreenLEDs_screen_destroy(void);
extern lv_obj_t * ui_ScreenLEDs;
extern lv_obj_t * ui_barMenu;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_uiStandListPanel;
extern lv_obj_t * ui_CheckboxStand1;
extern lv_obj_t * ui_CheckboxStand2;
extern lv_obj_t * ui_ColourWheel;
extern lv_obj_t * ui_AnimDropdown;
extern lv_obj_t * ui_LEDSettings;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenLEDs;
extern lv_obj_t * uic_uiStandListPanel;
extern lv_obj_t * uic_CheckboxStand1;
extern lv_obj_t * uic_CheckboxStand2;
extern lv_obj_t * uic_ColourWheel;
extern lv_obj_t * uic_AnimDropdown;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

